### ISSUE TITLE
can't support for ST3

### ISSUE THREAD

**Issue by zsytssk** [jamiesun/SublimeEvernote#16]
can't support for ST3

**Comment by duqcyxwd** [comment]
I have a problem when I try to install SublimeEvernote too.  I am using ST3 portalable Version.  This is the error: 

```
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
reloading plugin SublimeEvernote.html
reloading plugin SublimeEvernote.sublime_evernote
Traceback (most recent call last):
File "C:\My Program\Sublime Text Build 3047 x64\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
File "C:\My Program\Sublime Text Build 3047 x64\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
File "sublime_evernote in C:\My Program\Sublime Text Build 3047 x64\Data\Installed Packages\SublimeEvernote.sublime-package", line 41, in <module>
ImportError: No module named 'evernote'
```

**Comment by bordaigorl** [comment]
Hi,
I published a new version on Package control called simply "Evernote" which _only_ supports ST3 and adds new features.
I thought you may want to check it out:
https://github.com/bordaigorl/sublime-evernote
