### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HTTPS'

### ISSUE THREAD

**Issue by gurgeh** [jamiesun/SublimeEvernote#2]
After entering username and password nothing happens and the console prints the above error. I run Ubuntu Linux and Python 2.7.3.

The rest of the traceback is:

Traceback (most recent call last):
  File "./sublime_evernite.py", line 35, in on_passwd
  File "lib/evernote/edam/userstore/UserStore.py", line 399, in authenticate
  File "lib/evernote/edam/userstore/UserStore.py", line 411, in send_authenticate
  File "lib/thrift/transport/THttpClient.py", line 95, in _f
  File "lib/thrift/transport/THttpClient.py", line 103, in flush
  File "lib/thrift/transport/THttpClient.py", line 67, in open
AttributeError: 'module' object has no attribute 'HTTPS'

**Comment by gurgeh** [comment]
Oddly enough, it seems that the module in question is httplib, which do have HTTPS, when I try it from the REPL.

**Comment by jamiesun** [comment]
May be a conflict with the system environment

**Comment by dln** [comment]
Saw this as well on Ubuntu 12.04.

**Comment by inkenrat** [comment]
I have the same problem, does anybody have fixed it?

**Comment by KRostyslav** [comment]
Have fix this problem on Ubuntu 12.04?

**Comment by iderekliu** [comment]
The same problem on Ubuntu 12.04,How to fix it ?

**Comment by kirito-san** [comment]
The same problem here: Ubuntu 11.04; kernel: 2.6.38-16-generic; Python 2.7.1;

**Comment by daveroyer** [comment]
I am in the same boat. I was excited to try out Evernote support when I found the plugin but I get the exact same error running Linux Mint. Just for the heck of it I tried swapping in versions 0.8.0 and 0.9.0 of Thrift but got the same error. I would love to get to the bottom of this.

**Comment by gurgeh** [comment]
It might be related to this: https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/965371 Apparently Evernote's server has a mild bug and at some point the openssl guys decided that the right thing to do was to stop working around servers which exhibited that behaviour and just fail.
